### ISSUE TITLE
dst[0] = src[2] error in example-imagenet

### ISSUE THREAD

**Issue by AndreasRef** [mrzl/ofxDarknet#11]
When trying to run the example-imagenet I get an error related to the update function of ofQTKitGrabber

![screen shot 2017-01-25 at 11 43 14](https://cloud.githubusercontent.com/assets/9645568/22287565/a58c8f02-e2f3-11e6-90a5-3b245526620e.png)

Any idea what might be causing this?

**Comment by schwittlick** [comment]
Hm, this seems to be something related to your webcam setup, this is OF internal code that's having a problem. 
Can you run the webcam example that comes with OF without errors?

**Comment by AndreasRef** [comment]
Yes, also the example-yolo with webcam input without any issues

**Comment by schwittlick** [comment]
Interesting, since the webcam related code is identical in those two examples. I can't really do anything useful to help you, maybe clean and recompile the imagenet example, that sometimes does it for me when mystical errors occur.

**Comment by AndreasRef** [comment]
Okay, I'll try that. 
Btw: It runs for 1 frame before it crashes. If I comment out all darknet related stuff (and only draw the webcam image) it runs fine.

**Comment by schwittlick** [comment]
Any news on this, this seems really strange, as this OF code really has nothing to do with ofxDarknet. I'm simply copying the pixels from the webcam (https://github.com/mrzl/ofxDarknet/blob/master/src/ofxDarknet.cpp#L258-L272), so that should not have any effect here...

**Comment by genekogan** [comment]
@mrzl @AndreasRef i found the bug and fixed it in the `osx` branch. imagenet example now working for me (and very fast!). before i merge it to master i'll let marcel review it because there's a couple other changes there including having simplified the init process. marcel can you see if that works for windows and then we can merge it?  

the problem was that in `ofxDarknet::classify`, the internal pixels of the video were being resized without telling the video object -- so when it went to draw all the pixels, they were gone.  A quick fix is doing what's done in the `yolo` example and copying the pixels to a new `ofPixels` and resizing those.

**Comment by genekogan** [comment]
the changes are in [PR 13](https://github.com/mrzl/ofxDarknet/pull/13)

**Comment by genekogan** [comment]
also just realized, one possible issue with the merge is that one of the changes i made was fixing the following paths at the bottom of `yolo9000.cfg`.  

    tree=../../../data/cfg/9k.tree
    map=../../../data/cfg/coco9k.map

i think in windows you may need to get rid of the ../../..

**Comment by genekogan** [comment]
this should now be fixed as of [https://github.com/mrzl/ofxDarknet/pull/13](https://github.com/mrzl/ofxDarknet/pull/13), for windows and osx, on the master branch, verified working here. @AndreasRef give it a shot!
